---
title: "test BP-med interactive plot"
author: "Xing Song"
format: html
editor: visual
execute: 
  echo: false
  message: false
  warning: false
---

## load packages

```{r}
#| label: load-pkg
pacman::p_load(
  tidyverse,
  magrittr,
  stringr,
  broom,
  cowplot,
  ggrepel,
  kableExtra
)
bp_long<-readRDS(file.path("./data","bp_long_sample.rda"))
med<-readRDS(file.path("./data","med_long_sample.rda"))

id_sample<-6
```

```{r}
med_sample<-med %>% filter(id == id_sample)
med_sample_htn<-med_sample %>% filter(AntiHTN_ind==1)
med_sample_nhtn<-med_sample %>% filter(AntiHTN_ind==0)

bp_sample<-bp_long %>% 
  filter(id == id_sample) %>%
  filter(days_since_index >= -180 & days_since_index <= 365)

xmin<-min(med_sample$rx_start_since_index) - 10
xmax<-min(max(med_sample$rx_end_since_index),365) + 10
vpos<-unique(c(med_sample$rx_start_since_index,med_sample$rx_end_since_index))

# individual plot of med use
med_htn_plt<-ggplot(
  med_sample_htn,
  aes(
    y = in_or_name_s, yend = in_or_name_s
  )
) +
  geom_segment(
    aes(
      x = rx_start_since_index,
      xend = rx_start_since_index + rx_days,
      linewidth = rx_str
    ),
    color = "grey"
  ) +
  geom_point(
    aes(
      x = rx_start_since_index
    ),
    size = 3, color = 'red'
  ) +
  geom_text_repel(
    aes(
      x = rx_start_since_index,
      label = paste0(rx_str,'mg,',rx_freq_num)
    ),
    fontface = "bold"
  ) + 
  geom_vline(xintercept = 0,linetype=2) + 
  geom_vline(xintercept = vpos,linetype=3) + 
  scale_x_continuous('days since enroll',breaks = seq(xmin, xmax, by=30),limits=c(xmin,xmax)) + 
  theme_classic() + theme(legend.position = "none") +
  theme(axis.title = element_blank(), 
        axis.text.x = element_blank(),
        text = element_text(face="bold"))

med_nhtn_plt<-ggplot(
  med_sample_nhtn,
  aes(
    y = in_or_name_s, yend = in_or_name_s
  )
) +
  geom_segment(
    aes(
      x = rx_start_since_index,
      xend = rx_start_since_index + rx_days,
      linewidth = rx_str
    ),
    color = "grey"
  ) +
  geom_point(
    aes(
      x = rx_start_since_index
    ),
    size = 3, color = 'red'
  ) +
  geom_text_repel(
    aes(
      x = rx_start_since_index,
      label = paste0(rx_str,'mg,',rx_freq_num)
    ),
    fontface = "bold"
  ) + 
  geom_vline(xintercept = 0,linetype=2) + 
  geom_vline(xintercept = vpos,linetype=3) + 
  scale_x_continuous('days since enroll',breaks = seq(xmin, xmax, by=30),limits=c(xmin,xmax)) + 
  theme_classic() + theme(legend.position = "none") +
  theme(axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 45),
        text = element_text(face="bold"))

# individual plots of a random sample of size k
bp_plt<-ggplot(
  bp_sample,
  aes(x = days_since_index,
      y = bp_val,
      color = bp_type)
)+
  geom_line(aes(group = bp_type)) +
  geom_point(aes(shape = type),size=3,alpha=0.8) +
  geom_vline(xintercept = 0,linetype=2) + 
  geom_vline(xintercept = vpos,linetype=3) + 
  scale_x_continuous('days since enroll',breaks = seq(xmin, xmax, by=30),limits=c(xmin,xmax)) + 
  theme_classic() + theme(legend.position = "none") +
  theme(axis.title = element_blank(), 
        axis.text.x = element_blank(),
        text = element_text(face="bold"))

aligned_plots<-align_plots(bp_plt,med_htn_plt,med_nhtn_plt,align="v", axis="l")
plot_grid(aligned_plots[[1]], aligned_plots[[2]], aligned_plots[[3]], ncol = 1)
```
